spring:
  data:
    mongodb:
      database: bezkoder_db
      password: 10240309ll
      username: leon456
      uri: mongodb+srv://leon456:ZhRxkNkRXANvB4Qu@cluster0.g8y1m.gcp.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      port: 27017
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000